version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    volumes:
      - /home/vasa/data/:/data/pg
    ports:
      - 5432:5432
    networks:
      - my-pg-network
    environment:
      POSTGRES_PASSWORD: example

networks:
  my-pg-network:
    driver: bridge
